### PR TITLE
Add image slideshow, Convert "branches" to "subteams"

### PR DESCRIPTION
**Pull request by MatthewATaylor**
- Added image slideshow to media.html
     - With more pictures, multiple slideshows with different categories can be made.
- Replaced any instances of the word "branches" with the word "subteams."
- Added some useful links to the programming subteam page
     - Other subteam leaders can think about what to put on their subteam pages.

### CODE REVIEW

**Review by techguydave — CHANGES_REQUESTED** [review]
Looks good for the most part. The only thing I'd suggest is shrinking the image filesizes. Right now they're way too large at their original size. It took an average of 4 seconds to load, even on my computer with a wired network. It's definitely going to be a burden on phones.

Using an image compression program to cut the resolution in half should help a lot. If you don't intend on allowing clicking the images to load a larger version in a lightbox (which I think would be a good enhancement), I'd say you could even drop it to 25% of their current resolution.
image

**Comment by MatthewATaylor** [comment]
I just compressed all of the images, so their file sizes are now in the 50-200 KB range. I like the idea of enlarged images on click, so I'll work on that next.

**Review by techguydave — APPROVED** [review]
LGTM :rocket:

**Comment by techguydave** [comment]
Closes #14

**Pull request merged**
